### ISSUE TITLE
[BUG] Error in ECG_Baseline_Removal (line 92)     baseline(:,j)=pchip(center,baseline_points,1:1:L)'; %interpolate baseline

### ISSUE THREAD

**Issue by AmelGhizlene** [KIT-IBT/ECGdeli#2]
**Describe the bug**

**To Reproduce**
Important points to reproduce the behavior:
- In which function does the error appear?
- What signal are you using? Provide the signal if possible.
- Have you made any changes to the current version available on GitHub?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cnagel94** [comment]
Hello Amel,

thank you for your message. Could you describe the error a bit more precisely or provide an example signal so that we can reproduce the error and help you accordingly?

Thank you.
Claudia
